# ============================================================
# Load Visium Spatial RNA-seq Data into Seurat
# ============================================================

# This script demonstrates how sequencing-based spatial
# transcriptomics data (e.g., 10x Genomics Visium) are loaded
# into a Seurat object for downstream analysis.

# ------------------------------------------------------------
# Load libraries
# ------------------------------------------------------------
library(Seurat)
library(tidyverse)

# ------------------------------------------------------------
# Define data paths
# ------------------------------------------------------------
# Path should point to the output directory generated by
# Space Ranger (e.g., containing filtered_feature_bc_matrix
# and spatial image data).

visium_data_dir <- "path/to/visium/output_directory"

# ------------------------------------------------------------
# Load Visium data
# ------------------------------------------------------------
# This will load the gene expression matrix, spatial
# coordinates, and associated histology image.

spatial_obj <- Load10X_Spatial(
  data.dir = visium_data_dir,
  filename = "filtered_feature_bc_matrix.h5"
)

# ------------------------------------------------------------
# Initial object inspection
# ------------------------------------------------------------
# Inspect basic properties of the spatial object
spatial_obj

# Number of spots and detected genes
cat("Number of spatial spots:", ncol(spatial_obj), "\n")
cat("Number of detected genes:", nrow(spatial_obj), "\n")

# ------------------------------------------------------------
# Store metadata for reproducibility
# ------------------------------------------------------------
# Add sample-level metadata if needed
spatial_obj$sample_id <- "example_sample"

# ------------------------------------------------------------
# Save object for downstream steps
# ------------------------------------------------------------
saveRDS(
  spatial_obj,
  file = "01_data_import/visium_seurat_object_raw.rds"
)
